# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lcj's Notebook
email: honuluhfl9@gmail.com
description: "" # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lcj.ink" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
baseurl: ""
permalink: /:title/

disqus-shortname: lcj-ink

paginate: 5
paginate_path: "/page:num/"

#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass: 
  style: compressed

analytics: UA-158040317-1

version: 1.01
 
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  
prose:
  rooturl: ''
  siteurl: 'http://lcj.ink/starter/'
  relativeLinks: 'http://lcj.ink/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
